
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/bianzheng/software/cmake-4.0.2-linux-x86_64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
...
